language: csharp
solution: health-dashboard.sln
mono: none
dotnet: 2.1

# Specify which branches can be built on PR merge
branches:
  only:
    - master
    - development

script:
- dotnet restore

notifications:
    slack: sem5640-2018:QpZDGa0p8DOsuIzZBZn1jK0C
